### ISSUE TITLE
Fatal error: count(): Argument #1 ($var) must be of type Countable|array, OIK_lib given

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik-lib#7]
```Fatal error: Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, OIK_lib given in C:\apache\htdocs\wordpress\wp-content\plugins\oik\libs\bobbforms.php:270 
Stack trace: 
#0 C:\apache\htdocs\oikcom\wp-content\plugins\oik-lib\admin\oik-lib.php(92): bw_tablerow(Object(OIK_lib)) 
#1 C:\apache\htdocs\wordpress\wp-content\plugins\oik\libs\class-BW-.php(97): oik_lib_display_libraries() 
#2 C:\apache\htdocs\oikcom\wp-content\plugins\oik-lib\admin\oik-lib.php(38): BW_::oik_box(NULL, 'oik_lib_display...', 'Registered libr...', 'oik_lib_display...') 
#3 C:\apache\htdocs\oikcom\wp-includes\class-wp-hook.php(303): oik_lib_options_do_page('')
#4 C:\apache\htdocs\oikcom\wp-includes\class-wp-hook.php(327): WP_Hook->apply_filters('', Array) 
#5 C:\apache\htdocs\oikcom\wp-includes\plugin.php(470): WP_Hook->do_action(Array) 
#6 C:\apache\htdocs\oikcom\wp-admin\admin.php(259): do_action('settings_page_o...') 
#7 C:\apache\htdocs\oikcom\wp-admin\options-general.php(10): require_once('C:\\apache\\htdoc...') 
#8 {main} thrown in C:\apache\htdocs\wordpress\wp-content\plugins\oik\libs\bobbforms.php on line 270
```

**Comment by bobbingwide** [comment]
### Explanation
The parameter being passed to bw_tablerow() was `$data`, an instance of an OIK_lib object

### Solution
changing the code to pass the expected fields in an array resolves the issue. 

```
bw_tablerow( [ $data->library, $data->src, $data->deps, $data->version, $data->args ] );
```
